application: mygailapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /sig
  script: sig.py

- url: .*
  script: main.py
  secure: optional
