application: mygailapp2
version: 1
runtime: python
api_version: 1

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional
  
- url: /gail.css
  static_files: static/gail.css
  upload: static/gail.css
  secure: optional

- url: /fadeback.jpg
  static_files: static/fadeback.jpg
  upload: static/fadeback.jpg
  secure: optional

- url: /dologin
  script: main.py
  secure: always

- url: /password
  script: main.py
  secure: always

- url: /dopassword
  script: main.py
  secure: always
  
- url: /
  script: main.py
  secure: optional
  
- url: /gailadmin
  script: main.py
  secure: always
  login: admin

- url: /newprivkey
  script: main.py
  secure: always
  login: admin

- url: /edittemplates
  script: main.py
  secure: optional
  login: admin

- url: /updategooglesso
  script: main.py
  secure: always
  login: admin

- url: /dfile/(.*)
  script: dfile.py
  secure: optional

- url: /upload-dfile
  script: main.py
  secure: optional
  login: admin

- url: /del-dfile(.*)
  script: main.py
  secure: optional
  login: admin